### ISSUE TITLE
[CI] Add basic CI support

### ISSUE THREAD

**Issue by meshtag** [meshtag/GraphMLIR#27]
**Is your feature request related to a problem? Please describe.**
There is no CI to test PR and commit usability. 

**Describe the solution you'd like**
Create a simple GitHub Actions script to build and run the project. Make sure that `llvm` build is cached properly and we do not end up cloning and building `llvm` for each PR.

**Comment by meshtag** [comment]
@pk-218, does this interest you?

**Comment by whois-pk** [comment]
@meshtag Yes, I would like to take this up
